# Generated by Django 5.1.6 on 2025-04-24 19:37

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=15, unique=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=10)),
                ('guardian_name', models.CharField(blank=True, max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('village', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('geo_tag', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('farmer_consent', models.BooleanField(default=True)),
                ('id_type', models.CharField(blank=True, choices=[('aadhar', 'Aadhar Card'), ('driving_licence', 'Driving License'), ('voter_id', 'Voter ID'), ('pan_card', 'PAN Card')], max_length=50, null=True)),
                ('id_proof', models.FileField(blank=True, null=True, upload_to='farmer_documents/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='farmers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farm_name', models.CharField(max_length=100)),
                ('area_in_acres', models.FloatField()),
                ('sowing_date', models.DateField()),
                ('plant_name', models.CharField(max_length=100)),
                ('ownership', models.CharField(choices=[('OWNED', 'Owned'), ('LEASED', 'Leased')], max_length=10)),
                ('boundary', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('land_ownership', models.FileField(blank=True, null=True, upload_to='land_documents/')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farms', to='data_collection.farmer')),
            ],
        ),
    ]
