# Generated by Django 5.1.6 on 2025-04-25 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_collection', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farm',
            name='farm_name',
        ),
        migrations.RemoveField(
            model_name='farm',
            name='ownership',
        ),
        migrations.RemoveField(
            model_name='farmer',
            name='farmer_consent',
        ),
        migrations.RemoveField(
            model_name='farmer',
            name='guardian_name',
        ),
    ]
