# Generated by Django 5.1.6 on 2025-04-25 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_collection', '0002_remove_farm_farm_name_remove_farm_ownership_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farm',
            name='land_ownership',
        ),
        migrations.RemoveField(
            model_name='farm',
            name='plant_name',
        ),
        migrations.RemoveField(
            model_name='farm',
            name='sowing_date',
        ),
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(max_length=100)),
                ('number_of_plants', models.PositiveIntegerField()),
                ('area_in_acres', models.FloatField()),
                ('sowing_date', models.DateField()),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crops', to='data_collection.farm')),
            ],
        ),
    ]
