# Generated by Django 5.1.6 on 2025-04-25 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_collection', '0003_remove_farm_land_ownership_remove_farm_plant_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmer',
            name='id_proof',
        ),
        migrations.RemoveField(
            model_name='farmer',
            name='id_type',
        ),
    ]
